[package]
name = "xde"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
bitflags.workspace = true
blake3.workspace = true
bytes.workspace = true
compio.workspace = true
compio-buf.workspace = true
compio-io.workspace = true
compio-quic.workspace = true
compact_str.workspace = true
crc32c.workspace = true
event-listener.workspace = true
flume.workspace = true
futures-util.workspace = true
hickory-resolver = { version = "0.26", default-features = false, features = ["tokio", "system-config"] }
h3.workspace = true
http.workspace = true
http-body.workspace = true
httpdate.workspace = true
getifs = "0.6"
hyper.workspace = true
parking_lot.workspace = true
postcard.workspace = true
rustix.workspace = true
rustls.workspace = true
rustls-platform-verifier.workspace = true
send_wrapper.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
socket2.workspace = true
slotmap.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tokio = { version = "1", default-features = false, features = ["rt"] }
tracing.workspace = true
url.workspace = true
windows-sys.workspace = true

[dev-dependencies]
divan.workspace = true
proptest.workspace = true
rstest.workspace = true
tempfile.workspace = true
xde-test = { path = "../xde-test" }

[features]
default = []
blake3-rayon = ["blake3/rayon"]

[[bench]]
name = "ranges"
harness = false
